<?php

/**
 * Vue pour TaskController::listAction() du module SuiviProjet
 *
 * Est nécessaire du fait de la création du SuiviProjet\Controller\TaskController
 * qui remplace la méthode listAction() afin de prendre en compte le paramètre
 * GET :id Identifiant du projet dont il faut afficher les tâches.
 *
 * PHP version 5
 *
 * @category   Source
 * @package    SuiviProjet
 * @subpackage View
 * @author     Adrien Desfourneaux <adrien.desfourneaux@gmail.com>
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @link       https://github.com/adrien-desfourneaux/suivi-projet/tree/master/module/SuiviProjet/view/suivi-projet/task/list.phtml
 */

?>

<?php echo $this->render('dz-task/task/list.phtml'); ?>
