<?php

/**
 * Vue pour TaskController::showallAction() du module SuiviProjet
 *
 * Est nécessaire du fait de la création du SuiviProjet\Controller\TaskController
 * qui remplace la méthode showallAction() afin de prendre en compte le paramètre
 * GET :id Identifiant du projet dont il faut afficher les tâches.
 *
 * PHP version 5
 *
 * @category   Source
 * @package    SuiviProjet
 * @subpackage View
 * @author     Adrien Desfourneaux <adrien.desfourneaux@gmail.com>
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @link       https://github.com/adrien-desfourneaux/suivi-projet/tree/master/module/SuiviProjet/view/suivi-projet/task/showall.phtml
 */

?>

<?php echo $this->render('dz-tasK/task/showall.phtml'); ?>