<?php

/**
 * Vue pour l'action IndexController::indexAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    SuiviProjet
 * @subpackage View
 * @author     Adrien Desfourneaux <adrien.desfourneaux@gmail.com>
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @link       https://github.com/adrien-desfourneaux/suivi-projet
 */

?>

<?php

echo $this->dzProjectListWidget(
    array(
        'type'            => 'active',
        'hasDeleteAction' => false,
        'hasAddAction'    => false,
    )
);

?>
