<?php

/**
 * Vue pour l'action IndexController::indexAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    SuiviProjet
 * @subpackage View
 * @author     Adrien Desfourneaux <adrien.desfourneaux@gmail.com>
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @link       https://github.com/adrien-desfourneaux/suivi-projet/tree/master/module/SuiviProjet/view/suivi-projet/index/index.phtml
 */

?>

<h1>Liste des projets</h1>

<?php

echo $this->dzProjectShowAllWidget(
    array(
        'type' => 'active'
    )
);

?>
