<?php

/**
 * Vue pour le layout
 *
 * PHP version 5
 *
 * @category   Source
 * @package    SuiviProjet
 * @subpackage View
 * @author     Adrien Desfourneaux <adrien.desfourneaux@gmail.com>
 * @license    http://opensource.org/licenses/MIT The MIT License
 * @link       https://github.com/adrien-desfourneaux/suivi-projet/tree/master/module/SuiviProjet/view/layout/layout.phtml
 */

?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Suivi de projet')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
?>

<!-- Link -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
?>

<!-- Style -->
<?php echo $this->headStyle(); ?>

<!-- Script -->
<?php echo $this->headScript(); ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('suiviprojet') ?>">Suivi de projet</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <!--<li class="active"><a href="<?php //echo $this->url('suiviprojet') ?>">Suivi Projet</a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="identity-widget">
                <?php
                echo $this->dzUserIdentityWidget(
                    array(
                        'redirectLoginFailure' => $this->currentUrl(),
                        'redirectLoginSuccess' => $this->url('dzuser/account'),
                        'redirectLogout' => $this->url('suiviprojet'),
                        'hasRegistration' => false
                    )
                );
                ?>
            </div>
            <div style="clear:both"></div>
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
